import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Sawarabi_Mincho, Zen_Kaku_Gothic_New } from "next/font/google";
import Providers from "@/components/Providers";

const sawarabi = Sawarabi_Mincho({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--display-font",
});

const gothic = Zen_Kaku_Gothic_New({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${cn(sawarabi.variable)} ${cn(gothic.variable)} h-full w-full hover:cursor-default`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
